### ISSUE TITLE
Feature request: Compatibility with Git dependencies

### ISSUE THREAD

**Issue by aumetra** [ToBinio/cargo-features-manager#17]
I was interested in running the tool over a project that uses Git dependencies. Unfortunately it exits quite quickly telling me that it couldn't parse the version field.

To enable preliminary support, it would maybe be useful to just skip attempting to optimize Git dependencies and then slowly transition towards analyzing the manifest of Git dependencies.

**Comment by ToBinio** [comment]
just released a [new version](https://crates.io/crates/cargo-features-manager/0.5.3) which changes it so instead of stopping the tool when an error occurs it simply displays the error next to the dependency.

It seems to be [more complicated](https://github.com/Byron/gitoxide/discussions/1283) than expected to get the `cargo.toml` from a git repo that's why I only have this "fix" for now. will keep the issue open until it's resolved.

thanks a lot for opening the issue

**Comment by ToBinio** [comment]
I released a [new version](https://crates.io/crates/cargo-features-manager/0.6.0) which changes the way I get the feature data. This means that git dependencies should now work like other dependencies.
