### ISSUE TITLE
`*cargo-features-manager.keep` not always preserved in `cargo feature prune`

### ISSUE THREAD

**Issue by allada** [ToBinio/cargo-features-manager#37]
First, thank you for this package!

I spent a little time trimming some fat and ended up making the following PR:
https://github.com/TraceMachina/nativelink/commit/a501971f7da68c30768e7e36adbd1976ea43fbfc

The issue is that it appears that if you checkout this commit and run `cargo feature prune` it will keep trying to make the changes that `cargo-features-manager.keep` or `workspace.cargo-features-manager.keep` tries to get it to ignore.

I presented all configs in both `workspace` version and non-workspace version just to remove any doubt of our unique multi-compilation method system.

Repro case:
1. Checkout above listed commit,
2. Run `cargo feature prune` (takes  awhile)
3. ***Notice it changes all the things it should not be changing.

Happy to give more details if needed.

Thanks!

**Comment by ToBinio** [comment]
first of all thanks for the report, and the greater reproduction!

The issue was caused by how I differentiated between dev dependencies and normal ones. Which caused `*cargo-features-manager.keep` not to be applied to dev dependencies. 

after the fix prune still removed 3 more features, but they all seem correct.

nativelink-proto
tonic-build = { version = "0.12.0", features = ["prost"], default-features = false }

nativelink-store
aws-sdk-s3 = { version = "1.41.0", features = ["rt-tokio"], default-features = false }
serial_test = { version = "3.1.1", features = ["async"], default-features = false }

i pushed a fix to master if you wish you could try it out, else I will just publish a new version. If the issue sounds fixed to you

in case you want to test it

1. clone the repo
2. run `cargo install --path .`
3. run `cargo features prune` in your repo

Thanks again!

**Comment by allada** [comment]
Yes, this appears to fix it.

Thank you!
