### ISSUE TITLE
Can't navigate

### ISSUE THREAD

**Issue by gawlk** [ToBinio/cargo-features-manager#6]
Love the idea but only `Enter` seems to work. I cannot navigate at all.

On Mac OS and tried 3 different terminals.

**Comment by ToBinio** [comment]
I have just released a [new version](https://crates.io/crates/cargo-features-manager/0.4.0) which should fix it (please let me know if it does not)

it seems like the way I used `crossterm` had some issues on mac and linux
luckily I moved to `console` a few months ago but never published it since i though there was no reason to

big thanks for letting me know and for testing my project

**Comment by gawlk** [comment]
Awesome ! It works great 👍
